repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argocd
    namespace: argocd
    chart: argo/argo-cd
    version: "9.5.14"
    createNamespace: true
    wait: true
    values:
      - ./values/argocd-values.yaml

  - name: argocd-image-updater
    namespace: argocd
    chart: argo/argocd-image-updater
    version: "1.2.1"
    needs:
      - argocd/argocd
    wait: true
    values:
      - ./values/image-updater-values.yaml
