global:
  domain: argocd.host.local

configs:
  params:
    server.insecure: "true"

  cm:
    kustomize.enabled: "true"
    application.resourceTrackingMethod: annotation

  rbac:
    policy.default: role:readonly
    policy.csv: |
      p, role:admin, applications, *, */*, allow
      p, role:admin, clusters, *, *, allow
      p, role:admin, repositories, *, *, allow
      g, argocd-admins, role:admin

server:
  ingress:
    enabled: false

repoServer:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

applicationSet:
  replicas: 0 # disable ApplicationSet controller

notifications:
  enabled: false
