config:
  git.user: "argocd-image-updater"
  git.email: "argocd-image-updater@users.noreply.github.com"
  kube.events: false

  registries:
    - name: GAR US Central
      prefix: us-central1-docker.pkg.dev
      api_url: https://us-central1-docker.pkg.dev
      credentials: pullsecret:argocd/gar-credentials
      insecure: false

serviceAccount:
  create: true
  name: argocd-image-updater
